FROM postgres:16-alpine@sha256:721873c34ceb9f8d8fc265984940dc982404c105f19ad51be9fdc5970a6080ea AS vector
RUN apk add --no-cache build-base
ADD https://github.com/pgvector/pgvector.git#cab9da72c04353f143bb06b42ab70a403daac64a /tmp/pgvector
RUN cd /tmp/pgvector && make OPTFLAGS="" with_llvm=no && make install DESTDIR=/vector with_llvm=no

FROM postgres:16-alpine@sha256:721873c34ceb9f8d8fc265984940dc982404c105f19ad51be9fdc5970a6080ea
RUN apk upgrade --no-cache && rm -f /usr/local/bin/gosu /usr/local/bin/su-exec
COPY --from=vector /vector/usr/local/ /usr/local/
USER postgres
