#!/bin/sh
set -eu
umask 077
password=$(cat /run/secrets/redis_password)
# Secrets generated by operations:init are hex; arbitrary config syntax is rejected.
case "$password" in *[!a-f0-9]*|'') exit 1;; esac
printf 'requirepass %s\nappendonly yes\nappendfsync everysec\nmaxmemory 512mb\nmaxmemory-policy noeviction\nsave 900 1\n' "$password" > /data/relay.conf
exec redis-server /data/relay.conf
