-- Initial legacy-domain storage. Text JSON and epoch fields intentionally preserve import fidelity.
CREATE TABLE relay.users (
  id text NOT NULL,
  email text NOT NULL,
  name text NOT NULL,
  password text NOT NULL,
  created_at text NOT NULL,
  mfa_secret text,
  mfa_pending text,
  mfa_last_step bigint,
  PRIMARY KEY (id),
  UNIQUE (email)
);
CREATE TABLE relay.sessions (
  token text NOT NULL,
  user_id text NOT NULL,
  expires_at bigint NOT NULL,
  PRIMARY KEY (token)
);
CREATE TABLE relay.workspaces (
  id text NOT NULL,
  name text NOT NULL,
  settings text NOT NULL DEFAULT '{}',
  created_at text NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE relay.members (
  workspace_id text NOT NULL,
  user_id text NOT NULL,
  role text NOT NULL,
  PRIMARY KEY (workspace_id,user_id)
);
CREATE TABLE relay.invitations (
  id text NOT NULL,
  workspace_id text NOT NULL,
  email text NOT NULL,
  role text NOT NULL,
  token_hash text NOT NULL,
  expires_at bigint NOT NULL,
  accepted bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE (token_hash)
);
CREATE TABLE relay.projects (
  id text NOT NULL,
  workspace_id text NOT NULL,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  created_at text NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE relay.workflows (
  id text NOT NULL,
  workspace_id text NOT NULL,
  project_id text,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  graph text NOT NULL,
  revision bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL,
  updated_at text NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE relay.versions (
  id text NOT NULL,
  workflow_id text NOT NULL,
  revision bigint NOT NULL,
  name text NOT NULL,
  graph text NOT NULL,
  created_at text NOT NULL,
  workspace_id text NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (workflow_id,revision)
);
CREATE TABLE relay.agents (
  id text NOT NULL,
  workspace_id text NOT NULL,
  name text NOT NULL,
  config text NOT NULL,
  created_at text NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE relay.connections (
  id text NOT NULL,
  workspace_id text NOT NULL,
  name text NOT NULL,
  provider text NOT NULL,
  endpoint text NOT NULL,
  model text NOT NULL,
  secret text NOT NULL,
  config text NOT NULL DEFAULT '{}',
  created_at text NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE relay.tools (
  id text NOT NULL,
  workspace_id text NOT NULL,
  name text NOT NULL,
  kind text NOT NULL,
  config text NOT NULL,
  created_at text NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE relay.collections (
  id text NOT NULL,
  workspace_id text NOT NULL,
  name text NOT NULL,
  config text NOT NULL DEFAULT '{}',
  created_at text NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE relay.sources (
  id text NOT NULL,
  workspace_id text NOT NULL,
  collection_id text NOT NULL,
  name text NOT NULL,
  url text,
  status text NOT NULL,
  content text NOT NULL,
  progress bigint NOT NULL DEFAULT 0,
  error text,
  created_at text NOT NULL,
  index_generation bigint NOT NULL DEFAULT 0,
  index_lease_until bigint,
  index_lease_owner text,
  metadata text NOT NULL DEFAULT '{}',
  PRIMARY KEY (id)
);
CREATE TABLE relay.chunks (
  id text NOT NULL,
  workspace_id text NOT NULL,
  collection_id text NOT NULL,
  source_id text NOT NULL,
  ordinal bigint NOT NULL,
  content text NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE relay.memories (
  id text NOT NULL,
  workspace_id text NOT NULL,
  agent_id text NOT NULL,
  conversation_id text,
  content text NOT NULL,
  created_at text NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE relay.runs (
  id text NOT NULL,
  workspace_id text NOT NULL,
  workflow_id text,
  version_id text,
  graph text NOT NULL,
  input text NOT NULL,
  status text NOT NULL,
  mode text NOT NULL,
  conversation_id text,
  parent_id text,
  output text,
  error text,
  usage text NOT NULL DEFAULT '{}',
  created_at text NOT NULL,
  finished_at text,
  application_id text,
  active_ms bigint NOT NULL DEFAULT 0,
  active_since text,
  lease_owner text,
  lease_until bigint,
  lease_generation bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);
CREATE TABLE relay.steps (
  id text NOT NULL,
  run_id text NOT NULL,
  node_id text NOT NULL,
  status text NOT NULL,
  input text,
  output text,
  error text,
  attempt bigint NOT NULL DEFAULT 0,
  started_at text,
  finished_at text,
  checkpoint text,
  workspace_id text NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (run_id,node_id)
);
CREATE TABLE relay.events (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  run_id text NOT NULL,
  type text NOT NULL,
  node_id text,
  data text NOT NULL,
  created_at text NOT NULL,
  workspace_id text NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE relay.actions (
  id text NOT NULL,
  workspace_id text NOT NULL,
  run_id text NOT NULL,
  step_id text NOT NULL,
  tool_id text NOT NULL,
  status text NOT NULL,
  result text,
  error text,
  created_at text NOT NULL,
  side_effect bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);
CREATE TABLE relay.applications (
  id text NOT NULL,
  workspace_id text NOT NULL,
  workflow_id text NOT NULL,
  version_id text NOT NULL,
  name text NOT NULL,
  settings text NOT NULL,
  token_hash text NOT NULL,
  created_at text NOT NULL,
  graph_snapshot text,
  PRIMARY KEY (id)
);
CREATE TABLE relay.artifacts (
  id text NOT NULL,
  workspace_id text NOT NULL,
  run_id text,
  name text NOT NULL,
  content text NOT NULL,
  created_at text NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE relay.audit (
  id text NOT NULL,
  workspace_id text NOT NULL,
  user_id text NOT NULL,
  action text NOT NULL,
  target text NOT NULL,
  created_at text NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE relay.embeddings (
  chunk_id text NOT NULL,
  workspace_id text NOT NULL,
  collection_id text NOT NULL,
  model text NOT NULL,
  vector text NOT NULL,
  PRIMARY KEY (chunk_id)
);
CREATE TABLE relay.datasets (
  id text NOT NULL,
  workspace_id text NOT NULL,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  cases text NOT NULL,
  revision bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL,
  updated_at text NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE relay.evaluations (
  id text NOT NULL,
  workspace_id text NOT NULL,
  dataset_id text NOT NULL,
  dataset_snapshot text NOT NULL,
  workflow_id text NOT NULL,
  workflow_revision bigint NOT NULL,
  name text NOT NULL,
  status text NOT NULL,
  config text NOT NULL,
  summary text NOT NULL DEFAULT '{}',
  lease_owner text,
  lease_until bigint,
  created_at text NOT NULL,
  finished_at text,
  PRIMARY KEY (id)
);
CREATE TABLE relay.evaluation_cases (
  id text NOT NULL,
  evaluation_id text NOT NULL,
  ordinal bigint NOT NULL,
  input text NOT NULL,
  expected text,
  run_id text NOT NULL,
  judge_run_id text,
  status text NOT NULL DEFAULT 'queued',
  score double precision,
  result text,
  error text,
  workspace_id text NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (evaluation_id,ordinal)
);
CREATE TABLE relay.feedback (
  id text NOT NULL,
  workspace_id text NOT NULL,
  run_id text NOT NULL,
  user_id text NOT NULL,
  rating bigint NOT NULL,
  comment text NOT NULL DEFAULT '',
  created_at text NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (run_id,user_id)
);
CREATE TABLE relay.prompt_library (
  id text NOT NULL,
  workspace_id text NOT NULL,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  content text NOT NULL,
  revision bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL,
  updated_at text NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE relay.prompt_versions (
  id text NOT NULL,
  prompt_id text NOT NULL,
  revision bigint NOT NULL,
  content text NOT NULL,
  created_at text NOT NULL,
  workspace_id text NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (prompt_id,revision)
);
CREATE TABLE relay.schedules (
  id text NOT NULL,
  workspace_id text NOT NULL,
  workflow_id text NOT NULL,
  name text NOT NULL,
  interval_minutes bigint NOT NULL,
  input text NOT NULL,
  mode text NOT NULL,
  enabled bigint NOT NULL DEFAULT 1,
  next_at bigint NOT NULL,
  last_run_id text,
  created_at text NOT NULL,
  cron_expression text,
  timezone text NOT NULL DEFAULT 'UTC',
  PRIMARY KEY (id)
);
CREATE TABLE relay.auth_challenges (
  id text NOT NULL,
  user_id text NOT NULL,
  kind text NOT NULL,
  expires_at bigint NOT NULL,
  attempts bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);
CREATE TABLE relay.reset_tokens (
  token_hash text NOT NULL,
  user_id text NOT NULL,
  expires_at bigint NOT NULL,
  PRIMARY KEY (token_hash)
);
CREATE TABLE relay.oidc_states (
  id text NOT NULL,
  verifier text NOT NULL,
  nonce text NOT NULL,
  expires_at bigint NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE relay.external_identities (
  issuer text NOT NULL,
  subject text NOT NULL,
  user_id text NOT NULL,
  PRIMARY KEY (issuer,subject)
);
CREATE TABLE relay.integration_catalog (
  id text NOT NULL,
  name text NOT NULL,
  kind text NOT NULL,
  description text NOT NULL,
  config text NOT NULL,
  category text NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE relay.mfa_recovery (
  user_id text NOT NULL,
  code_hash text NOT NULL,
  PRIMARY KEY (user_id,code_hash)
);
CREATE TABLE relay.model_cache (
  workspace_id text NOT NULL,
  cache_key text NOT NULL,
  response text NOT NULL,
  expires_at text NOT NULL,
  PRIMARY KEY (workspace_id,cache_key)
);
CREATE TABLE relay.tool_approvals (
  id text NOT NULL,
  step_id text NOT NULL,
  tool_id text NOT NULL,
  tool_name text NOT NULL,
  input text NOT NULL,
  input_hash text NOT NULL,
  status text NOT NULL,
  created_at text NOT NULL,
  workspace_id text NOT NULL,
  PRIMARY KEY (id)
);
ALTER TABLE relay.sessions ADD FOREIGN KEY (user_id) REFERENCES relay.users(id) ON DELETE CASCADE;
ALTER TABLE relay.workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.workspaces FORCE ROW LEVEL SECURITY;
CREATE POLICY workspaces_workspace ON relay.workspaces USING (id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (id=nullif(current_setting('relay.workspace_id',true),''));
ALTER TABLE relay.members ADD FOREIGN KEY (user_id) REFERENCES relay.users(id) ON DELETE NO ACTION;
ALTER TABLE relay.members ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE CASCADE;
ALTER TABLE relay.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.members FORCE ROW LEVEL SECURITY;
CREATE POLICY members_workspace ON relay.members USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX members_tenant ON relay.members(workspace_id);
ALTER TABLE relay.invitations ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.invitations FORCE ROW LEVEL SECURITY;
CREATE POLICY invitations_workspace ON relay.invitations USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX invitations_tenant ON relay.invitations(workspace_id);
ALTER TABLE relay.projects ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.projects FORCE ROW LEVEL SECURITY;
CREATE POLICY projects_workspace ON relay.projects USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX projects_tenant ON relay.projects(workspace_id);
ALTER TABLE relay.workflows ADD FOREIGN KEY (project_id) REFERENCES relay.projects(id) ON DELETE NO ACTION;
ALTER TABLE relay.workflows ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.workflows ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.workflows FORCE ROW LEVEL SECURITY;
CREATE POLICY workflows_workspace ON relay.workflows USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX workflows_tenant ON relay.workflows(workspace_id);
ALTER TABLE relay.versions ADD FOREIGN KEY (workflow_id) REFERENCES relay.workflows(id) ON DELETE CASCADE;
ALTER TABLE relay.versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.versions FORCE ROW LEVEL SECURITY;
CREATE POLICY versions_workspace ON relay.versions USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX versions_tenant ON relay.versions(workspace_id);
ALTER TABLE relay.agents ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.agents FORCE ROW LEVEL SECURITY;
CREATE POLICY agents_workspace ON relay.agents USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX agents_tenant ON relay.agents(workspace_id);
ALTER TABLE relay.connections ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.connections FORCE ROW LEVEL SECURITY;
CREATE POLICY connections_workspace ON relay.connections USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX connections_tenant ON relay.connections(workspace_id);
ALTER TABLE relay.tools ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.tools ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.tools FORCE ROW LEVEL SECURITY;
CREATE POLICY tools_workspace ON relay.tools USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX tools_tenant ON relay.tools(workspace_id);
ALTER TABLE relay.collections ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.collections FORCE ROW LEVEL SECURITY;
CREATE POLICY collections_workspace ON relay.collections USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX collections_tenant ON relay.collections(workspace_id);
ALTER TABLE relay.sources ADD FOREIGN KEY (collection_id) REFERENCES relay.collections(id) ON DELETE CASCADE;
ALTER TABLE relay.sources ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.sources FORCE ROW LEVEL SECURITY;
CREATE POLICY sources_workspace ON relay.sources USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX sources_tenant ON relay.sources(workspace_id);
ALTER TABLE relay.chunks ADD FOREIGN KEY (source_id) REFERENCES relay.sources(id) ON DELETE CASCADE;
ALTER TABLE relay.chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.chunks FORCE ROW LEVEL SECURITY;
CREATE POLICY chunks_workspace ON relay.chunks USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX chunks_tenant ON relay.chunks(workspace_id);
ALTER TABLE relay.memories ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.memories FORCE ROW LEVEL SECURITY;
CREATE POLICY memories_workspace ON relay.memories USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX memories_tenant ON relay.memories(workspace_id);
ALTER TABLE relay.runs ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.runs FORCE ROW LEVEL SECURITY;
CREATE POLICY runs_workspace ON relay.runs USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX runs_tenant ON relay.runs(workspace_id);
ALTER TABLE relay.steps ADD FOREIGN KEY (run_id) REFERENCES relay.runs(id) ON DELETE CASCADE;
ALTER TABLE relay.steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.steps FORCE ROW LEVEL SECURITY;
CREATE POLICY steps_workspace ON relay.steps USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX steps_tenant ON relay.steps(workspace_id);
ALTER TABLE relay.events ADD FOREIGN KEY (run_id) REFERENCES relay.runs(id) ON DELETE CASCADE;
ALTER TABLE relay.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.events FORCE ROW LEVEL SECURITY;
CREATE POLICY events_workspace ON relay.events USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX events_tenant ON relay.events(workspace_id);
ALTER TABLE relay.actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.actions FORCE ROW LEVEL SECURITY;
CREATE POLICY actions_workspace ON relay.actions USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX actions_tenant ON relay.actions(workspace_id);
ALTER TABLE relay.applications ADD FOREIGN KEY (version_id) REFERENCES relay.versions(id) ON DELETE NO ACTION;
ALTER TABLE relay.applications ADD FOREIGN KEY (workflow_id) REFERENCES relay.workflows(id) ON DELETE NO ACTION;
ALTER TABLE relay.applications ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.applications FORCE ROW LEVEL SECURITY;
CREATE POLICY applications_workspace ON relay.applications USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX applications_tenant ON relay.applications(workspace_id);
ALTER TABLE relay.artifacts ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.artifacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.artifacts FORCE ROW LEVEL SECURITY;
CREATE POLICY artifacts_workspace ON relay.artifacts USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX artifacts_tenant ON relay.artifacts(workspace_id);
ALTER TABLE relay.audit ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.audit FORCE ROW LEVEL SECURITY;
CREATE POLICY audit_workspace ON relay.audit USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX audit_tenant ON relay.audit(workspace_id);
ALTER TABLE relay.embeddings ADD FOREIGN KEY (chunk_id) REFERENCES relay.chunks(id) ON DELETE CASCADE;
ALTER TABLE relay.embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.embeddings FORCE ROW LEVEL SECURITY;
CREATE POLICY embeddings_workspace ON relay.embeddings USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX embeddings_tenant ON relay.embeddings(workspace_id);
ALTER TABLE relay.datasets ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.datasets ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.datasets FORCE ROW LEVEL SECURITY;
CREATE POLICY datasets_workspace ON relay.datasets USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX datasets_tenant ON relay.datasets(workspace_id);
ALTER TABLE relay.evaluations ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.evaluations FORCE ROW LEVEL SECURITY;
CREATE POLICY evaluations_workspace ON relay.evaluations USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX evaluations_tenant ON relay.evaluations(workspace_id);
ALTER TABLE relay.evaluation_cases ADD FOREIGN KEY (evaluation_id) REFERENCES relay.evaluations(id) ON DELETE CASCADE;
ALTER TABLE relay.evaluation_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.evaluation_cases FORCE ROW LEVEL SECURITY;
CREATE POLICY evaluation_cases_workspace ON relay.evaluation_cases USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX evaluation_cases_tenant ON relay.evaluation_cases(workspace_id);
ALTER TABLE relay.feedback ADD FOREIGN KEY (run_id) REFERENCES relay.runs(id) ON DELETE CASCADE;
ALTER TABLE relay.feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.feedback FORCE ROW LEVEL SECURITY;
CREATE POLICY feedback_workspace ON relay.feedback USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX feedback_tenant ON relay.feedback(workspace_id);
ALTER TABLE relay.prompt_library ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.prompt_library ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.prompt_library FORCE ROW LEVEL SECURITY;
CREATE POLICY prompt_library_workspace ON relay.prompt_library USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX prompt_library_tenant ON relay.prompt_library(workspace_id);
ALTER TABLE relay.prompt_versions ADD FOREIGN KEY (prompt_id) REFERENCES relay.prompt_library(id) ON DELETE CASCADE;
ALTER TABLE relay.prompt_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.prompt_versions FORCE ROW LEVEL SECURITY;
CREATE POLICY prompt_versions_workspace ON relay.prompt_versions USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX prompt_versions_tenant ON relay.prompt_versions(workspace_id);
ALTER TABLE relay.schedules ADD FOREIGN KEY (workflow_id) REFERENCES relay.workflows(id) ON DELETE CASCADE;
ALTER TABLE relay.schedules ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE NO ACTION;
ALTER TABLE relay.schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.schedules FORCE ROW LEVEL SECURITY;
CREATE POLICY schedules_workspace ON relay.schedules USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX schedules_tenant ON relay.schedules(workspace_id);
ALTER TABLE relay.external_identities ADD FOREIGN KEY (user_id) REFERENCES relay.users(id) ON DELETE NO ACTION;
ALTER TABLE relay.mfa_recovery ADD FOREIGN KEY (user_id) REFERENCES relay.users(id) ON DELETE NO ACTION;
ALTER TABLE relay.model_cache ADD FOREIGN KEY (workspace_id) REFERENCES relay.workspaces(id) ON DELETE CASCADE;
ALTER TABLE relay.model_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.model_cache FORCE ROW LEVEL SECURITY;
CREATE POLICY model_cache_workspace ON relay.model_cache USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX model_cache_tenant ON relay.model_cache(workspace_id);
ALTER TABLE relay.tool_approvals ADD FOREIGN KEY (step_id) REFERENCES relay.steps(id) ON DELETE CASCADE;
ALTER TABLE relay.tool_approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay.tool_approvals FORCE ROW LEVEL SECURITY;
CREATE POLICY tool_approvals_workspace ON relay.tool_approvals USING (workspace_id=nullif(current_setting('relay.workspace_id',true),'')) WITH CHECK (workspace_id=nullif(current_setting('relay.workspace_id',true),''));
CREATE INDEX tool_approvals_tenant ON relay.tool_approvals(workspace_id);
ALTER TABLE relay.invitations ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.projects ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.workflows ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.versions ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.agents ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.connections ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.tools ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.collections ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.sources ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.chunks ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.memories ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.runs ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.steps ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.events ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.actions ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.applications ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.artifacts ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.audit ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.datasets ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.evaluations ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.evaluation_cases ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.feedback ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.prompt_library ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.prompt_versions ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.schedules ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.tool_approvals ADD UNIQUE(workspace_id,id);
ALTER TABLE relay.workflows ADD FOREIGN KEY(workspace_id,project_id) REFERENCES relay.projects(workspace_id,id) ON DELETE NO ACTION;
ALTER TABLE relay.versions ADD FOREIGN KEY(workspace_id,workflow_id) REFERENCES relay.workflows(workspace_id,id) ON DELETE CASCADE;
ALTER TABLE relay.sources ADD FOREIGN KEY(workspace_id,collection_id) REFERENCES relay.collections(workspace_id,id) ON DELETE CASCADE;
ALTER TABLE relay.chunks ADD FOREIGN KEY(workspace_id,source_id) REFERENCES relay.sources(workspace_id,id) ON DELETE CASCADE;
ALTER TABLE relay.steps ADD FOREIGN KEY(workspace_id,run_id) REFERENCES relay.runs(workspace_id,id) ON DELETE CASCADE;
ALTER TABLE relay.events ADD FOREIGN KEY(workspace_id,run_id) REFERENCES relay.runs(workspace_id,id) ON DELETE CASCADE;
ALTER TABLE relay.applications ADD FOREIGN KEY(workspace_id,version_id) REFERENCES relay.versions(workspace_id,id) ON DELETE NO ACTION;
ALTER TABLE relay.applications ADD FOREIGN KEY(workspace_id,workflow_id) REFERENCES relay.workflows(workspace_id,id) ON DELETE NO ACTION;
ALTER TABLE relay.embeddings ADD FOREIGN KEY(workspace_id,chunk_id) REFERENCES relay.chunks(workspace_id,id) ON DELETE CASCADE;
ALTER TABLE relay.evaluation_cases ADD FOREIGN KEY(workspace_id,evaluation_id) REFERENCES relay.evaluations(workspace_id,id) ON DELETE CASCADE;
ALTER TABLE relay.feedback ADD FOREIGN KEY(workspace_id,run_id) REFERENCES relay.runs(workspace_id,id) ON DELETE CASCADE;
ALTER TABLE relay.prompt_versions ADD FOREIGN KEY(workspace_id,prompt_id) REFERENCES relay.prompt_library(workspace_id,id) ON DELETE CASCADE;
ALTER TABLE relay.schedules ADD FOREIGN KEY(workspace_id,workflow_id) REFERENCES relay.workflows(workspace_id,id) ON DELETE CASCADE;
ALTER TABLE relay.tool_approvals ADD FOREIGN KEY(workspace_id,step_id) REFERENCES relay.steps(workspace_id,id) ON DELETE CASCADE;
ALTER TABLE relay.members ADD CHECK(role IN ('owner','administrator','editor','viewer'));
