ALTER TABLE runs ADD COLUMN lease_owner TEXT;
ALTER TABLE runs ADD COLUMN lease_until INTEGER;
ALTER TABLE runs ADD COLUMN lease_generation INTEGER NOT NULL DEFAULT 0;
CREATE INDEX run_claim ON runs(status,lease_until,created_at);
CREATE TABLE workers(id TEXT PRIMARY KEY,name TEXT NOT NULL,started_at INTEGER NOT NULL,heartbeat INTEGER NOT NULL,capacity INTEGER NOT NULL,active INTEGER NOT NULL DEFAULT 0);
ALTER TABLE sources ADD COLUMN index_generation INTEGER NOT NULL DEFAULT 0;
CREATE TABLE embeddings(chunk_id TEXT PRIMARY KEY REFERENCES chunks(id) ON DELETE CASCADE,workspace_id TEXT NOT NULL,collection_id TEXT NOT NULL,model TEXT NOT NULL,vector TEXT NOT NULL);
CREATE INDEX embedding_scope ON embeddings(workspace_id,collection_id,model);
CREATE TABLE datasets(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',cases TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE evaluations(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),dataset_id TEXT NOT NULL,dataset_snapshot TEXT NOT NULL,workflow_id TEXT NOT NULL,workflow_revision INTEGER NOT NULL,name TEXT NOT NULL,status TEXT NOT NULL,config TEXT NOT NULL,summary TEXT NOT NULL DEFAULT '{}',lease_owner TEXT,lease_until INTEGER,created_at TEXT NOT NULL,finished_at TEXT);
CREATE TABLE evaluation_cases(id TEXT PRIMARY KEY,evaluation_id TEXT NOT NULL REFERENCES evaluations(id) ON DELETE CASCADE,ordinal INTEGER NOT NULL,input TEXT NOT NULL,expected TEXT,run_id TEXT NOT NULL,judge_run_id TEXT,status TEXT NOT NULL DEFAULT 'queued',score REAL,result TEXT,error TEXT,UNIQUE(evaluation_id,ordinal));
CREATE INDEX evaluation_workspace ON evaluations(workspace_id,created_at);
CREATE TABLE feedback(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,user_id TEXT NOT NULL,rating INTEGER NOT NULL CHECK(rating BETWEEN -1 AND 1),comment TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,UNIQUE(run_id,user_id));
CREATE TABLE prompt_library(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',content TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE prompt_versions(id TEXT PRIMARY KEY,prompt_id TEXT NOT NULL REFERENCES prompt_library(id) ON DELETE CASCADE,revision INTEGER NOT NULL,content TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(prompt_id,revision));
CREATE TABLE schedules(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),workflow_id TEXT NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,name TEXT NOT NULL,interval_minutes INTEGER NOT NULL,input TEXT NOT NULL,mode TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,next_at INTEGER NOT NULL,last_run_id TEXT,created_at TEXT NOT NULL);
ALTER TABLE users ADD COLUMN mfa_secret TEXT;
ALTER TABLE users ADD COLUMN mfa_pending TEXT;
CREATE TABLE auth_challenges(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,kind TEXT NOT NULL,expires_at INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 0);
CREATE TABLE reset_tokens(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE oidc_states(id TEXT PRIMARY KEY,verifier TEXT NOT NULL,nonce TEXT NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE external_identities(issuer TEXT NOT NULL,subject TEXT NOT NULL,user_id TEXT NOT NULL REFERENCES users(id),PRIMARY KEY(issuer,subject));
CREATE TABLE integration_catalog(id TEXT PRIMARY KEY,name TEXT NOT NULL,kind TEXT NOT NULL,description TEXT NOT NULL,config TEXT NOT NULL,category TEXT NOT NULL);
INSERT INTO migrations VALUES(4,datetime('now'));
